### PR TITLE
Fix mistake in README example

### PR DESCRIPTION
**Pull request by cardoso**
Great lib 👍

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
Cool, thanks a lot!

**Comment by wdcurry** [comment]
not worth creating a new issue for: but the pod instruction should read: 

pod 'Stryng'

{the single quotes are missing...}

And kudos for this, the regression of string utility in Swift is mind-boggling.

**Comment by BalestraPatrick** [comment]
@wdcurry Fixed it, thanks for noticing!

**Comment by wdcurry** [comment]
You are most welcome.. i look forward to trying out the repo, as I am definitely tired of fighting Swift Strungs  (can't really call them strings any longer, as they seem just so strung outl ;)

**Pull request merged**
